server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.178.101:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://192.168.178.101:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: "GMT+8"

minio:
  endpoint: http://192.168.178.101:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: lease

# 可以将参数对象的属性在doc中展平处理
springdoc:
  default-flat-param-object: true

